### ISSUE TITLE
Missing Create, Update and Delete examples

### ISSUE THREAD

**Issue by ekwus** [deriegle/dart-airtable#1] opened 2020-08-25 22:22 UTC
Hey would it be possible to add examples of more of the operations?

I'm able to get all records fine but I've not been able to create record. I know my Airtable/Api Key/etc are good as I can create records using Postman both with a simple blank record (minimal json) and a complete one.

I'm using the following code

var row = AirtableRecord(
    fields: [
      //AirtableRecordField(fieldName: 'Title', value: 'API Test Course'), // Fails regardless if this field is included or not
    ],
  );

var result = await _airtable.createRecord(_recordName, row);

However I always get back a null. The same _airtable object works for the getAllRecords method.

**Comment by ekwus** [comment] 2020-08-26 15:24
Create and Update calls have incorrect JSON formatting. The fields 'id' and 'createdTime' need to be removed when posting a record back to Airtable.

I've fixed this in my fork and will make a pull request.

**Comment by magnussp** [comment] 2020-10-30 13:53
@ekwus I ran into the same issue and was glad to see you pull request. I tried your fork by adding the following in `pubspec.yml`
```
dependencies:
  # dart_airtable: ^0.1.1
  dart_airtable:
    git:
      url: https://github.com/ekwus/dart-airtable.git
```

However the `createRecord` function still always returns `null`.  My code is basically following your example in the comment above.

**Comment by magnussp** [comment] 2020-10-30 14:32
Upon further inspection and some debug added to the lib I can see that the issue is because of `INVALID_VALUE_FOR_COLUMN` error from Airtables API.

This was for me solved if I per Airtable API instructions added the parameter `typecast` and set it to `true` in the body of the POST.

**Comment by deriegle** [comment] 2020-10-30 19:14
It has been a minute since I've worked on this library. I've merged the two PRs that you both put up, so hopefully that helps. It's been released as `v0.1.2`. 

I'll try to add some more examples to the `README` in this repo, but you can also take a look at the latest generated docs from pub dev for some documentation as well.

https://pub.dev/documentation/dart_airtable/latest/dart_airtable/Airtable-class.html

**Comment by magnussp** [comment] 2020-10-30 19:16
Docs are excellent, thx @deriegle

**Comment by ekwus** [comment] 2020-10-30 21:22
Hey I did mean to get back to adding some more docs/example in to a pull requests but haven't found the time yet. In the end it was the bug that was causing the null and not the lack of docs to guide me :-).

**Closed** 2020-10-31 16:47 UTC
